# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c81d4034efb0372f7ba80a04e5020c5a2a11432d07c3b8181dcdbf1f53e890658e9696eb8cf99778a92b77b9d493cefec29a7f57667d994e593e8f04a9b304f

test:
  secret_key_base: 150c3e43dd3f3f12643694d511605a7afee1d3df8743ef69da340fc836f565bab27b9f7c90f1f666c257e7600bb1e4b0b0caae26a3d3982beb978913fb22782e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
